name: AdvancedStaff
main: xoapp\advanced\Loader
api: 4.0.0
version: 1.0.0
author: Xoapp

permissions:
  advanced.staff:
    default: op
  advanced.unmute:
    default: op
  advanced.banlist:
    default: op
  advanced.ban:
    default: op
  advanced.mute:
    default: op
  advanced.unban:
    default: op
  prototype.command:
    default: op
  advanced.alts:
    default: op
  advanced.ban-ip:
    default: op